# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

vendas_1sem.extend(vendas_2sem)
maior_valor = max(vendas_1sem)
menor_valor = min(vendas_1sem)
print('O maior valor de vendas no ano foi de: R$ {}'.format(maior_valor))
print('O menor valor de vendas no ano foi de: R$ {}'.format(menor_valor))

"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.

Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""
print(meses)
print(vendas_1sem)
i_maior_valor = vendas_1sem.index(maior_valor)
print(i_maior_valor)
i_menor_valor = vendas_1sem.index(menor_valor)
print(i_menor_valor)
print('O maior valor de vendas ocorreu no mês de: {} com {} vendas.'.format(meses[i_maior_valor], maior_valor))
print('O pior valor de vendas ocorreu no mês de: {} com {} vendas.'.format(meses[i_menor_valor], menor_valor))
fat_total = sum(vendas_1sem)
print('O faturamento total do ano foi de: R$ {}'.format(fat_total))
total = fat_total - maior_valor
percentual = (maior_valor / fat_total)
print('O faturamento do ano sem considerar o melhor mês foi de: R$ {}'.format(total))
print('O melhor mes foi de {:.2%}'.format(percentual))


"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""

top3 = []
print(vendas_1sem)
top3.append(maior_valor)
print(top3)
vendas_1sem.remove(maior_valor)
maior_valor = max(vendas_1sem)
top3.append(maior_valor)
vendas_1sem.remove(maior_valor)
maior_valor = max(vendas_1sem)
top3.append(maior_valor)
print('Os 3 melhores meses de vendas foram: {}'.format(top3))